name: Build React on S3
on:
  push:
      branches:
        - main

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main  # リポジトリをチェックアウト
        
      - name: Install Dependencies
        run: npm install
    
      - name: Update Env
        run: export CI=false
      
      - name: Build
        run: npm run build  # React ビルド
        env:
          CI: false

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 build s3://$S3_UPLOAD_BUCKET
